---
kolla_ansible_branch: "stable/2025.1"

# OpenShift Cluster Configuration
cluster_name: "test-ocp"
cluster_domain: "arrakis-ocp.com"

# Discovery ISO Configuration
# You'll get this URL from the Assisted Installer UI after creating an InfraEnv
discovery_iso_url: "https://api.openshift.com/api/assisted-images/bytoken/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTk3NzIyMDIsInN1YiI6ImNiNjVhMzk0LWYxOWMtNDI3OS05YjMxLTgxZTNlNGY4NmFkZiJ9.c4x8QlStkJ4FDW9dB7ESXWiglR1givd46BSq_5nxa-c/4.19/x86_64/full.iso"
discovery_iso_path: "/var/lib/libvirt/images/discovery_image_{{ cluster_name }}.iso"

# VM Configuration
vm_count: 3
vm_name_prefix: "{{ cluster_name }}-node"
vm_memory_mb: 65536  # 64GB
vm_vcpus: 16
vm_disk_size_gb: 120

# Storage Configuration
libvirt_pool: "default"
libvirt_images_path: "/var/lib/libvirt/images"

# Network Configuration
networks:
  - name: "virbr-mgmt"
    network: "192.168.100.0/24"
    bridge: "virbr-mgmt"
  - name: "virbr-storage"
    network: "192.168.101.0/24"
    bridge: "virbr-storage"
  - name: "virbr-provider"
    network: "192.168.102.0/24"
    bridge: "virbr-provider"

# Primary network for OpenShift (used for boot)
primary_network: "virbr-mgmt"

# VM Definitions
vms:
  - name: "{{ vm_name_prefix }}-01"
    memory: "{{ vm_memory_mb }}"
    vcpus: "{{ vm_vcpus }}"
    disk_size: "{{ vm_disk_size_gb }}"
  - name: "{{ vm_name_prefix }}-02"
    memory: "{{ vm_memory_mb }}"
    vcpus: "{{ vm_vcpus }}"
    disk_size: "{{ vm_disk_size_gb }}"
  - name: "{{ vm_name_prefix }}-03"
    memory: "{{ vm_memory_mb }}"
    vcpus: "{{ vm_vcpus }}"
    disk_size: "{{ vm_disk_size_gb }}"

# OpenStack configuration
openstack_release: "2025.1"
kolla_base_distro: "rocky"
kolla_install_type: "binary"

# SSH key configuration
vm_key_user: ansible
vm_key_dir: "/home/{{ vm_key_user }}/.ssh"
vm_key_priv: "{{ vm_key_dir }}/id_ed25519"
vm_key_pub: "{{ vm_key_priv }}.pub"

# Retry configuration
max_retries: 3
retry_delay: 10
kvm_host_ip: 192.168.100.1

# Network interface names
primary_network_interface: "ens3"

# Kolla VIP addresses
kolla_internal_vip_address: "192.168.100.200"
kolla_external_vip_address: "192.168.100.200"
