---
# Master playbook - runs complete end-to-end deployment
- name: Complete OpenStack Deployment
  import_playbook: deploy_vms.yml
  tags: [vms]

- name: Deploy OpenStack with Kolla-Ansible
  import_playbook: deploy_openstack.yml
  tags: [openstack]

- name: Validate OpenStack Deployment
  import_playbook: validate_openstack.yml
  tags: [validate]
