---
- name: Generate admin OpenStack credentials file
  ansible.builtin.shell: |
    ADMIN_PASS=$(sudo grep keystone_admin_password /etc/kolla/passwords.yml | awk '{print $2}')
    sudo tee /etc/kolla/admin-openrc.sh > /dev/null << ENVEOF
    export OS_PROJECT_DOMAIN_NAME=Default
    export OS_USER_DOMAIN_NAME=Default
    export OS_PROJECT_NAME=admin
    export OS_USERNAME=admin
    export OS_PASSWORD=$ADMIN_PASS
    export OS_AUTH_URL=http://192.168.100.200:5000/v3
    export OS_IDENTITY_API_VERSION=3
    export OS_REGION_NAME=RegionOne
    export OS_INTERFACE=internal
    ENVEOF
    sudo chmod 644 /etc/kolla/admin-openrc.sh
  args:
    creates: /etc/kolla/admin-openrc.sh
  become: true
  become_user: ansible

- name: Verify admin credentials file was created
  ansible.builtin.stat:
    path: /etc/kolla/admin-openrc.sh
  register: admin_rc_stat

- name: Display credentials file status
  ansible.builtin.debug:
    msg: "Admin credentials file created: {{ admin_rc_stat.stat.exists }}"
