---
- name: Gather facts after cloud-init
  ansible.builtin.setup:

- name: Wait for cloud-init and package locks
  ansible.builtin.import_tasks: wait_for_cloud_init.yml
  tags: [wait]

- name: Import Docker installation tasks FIRST
  ansible.builtin.import_tasks: docker.yml
  tags: [docker]

- name: Import system configuration tasks AFTER Docker
  ansible.builtin.import_tasks: system_config.yml
  tags: [system]

- name: Import NTP client configuration tasks
  ansible.builtin.import_tasks: ntp_client.yml
  tags: [ntp]

- name: Import networking configuration tasks
  ansible.builtin.import_tasks: networking.yml
  tags: [networking]
