---
- name: Wait for cloud-init to complete
  ansible.builtin.command: cloud-init status --wait
  changed_when: false
  register: cloud_init_status
  failed_when: false

- name: Display cloud-init status
  ansible.builtin.debug:
    var: cloud_init_status.stdout

- name: Wait additional time for package manager to release locks
  ansible.builtin.pause:
    seconds: 30
    prompt: "Waiting for package manager locks to clear..."
