---
- name: Source admin credentials
  ansible.builtin.shell: |
    source /etc/kolla/admin-openrc.sh
    env | grep ^OS_
  register: admin_env
  changed_when: false

- name: Set OpenStack environment facts
  ansible.builtin.set_fact:
    openstack_env: "{{ dict(admin_env.stdout_lines | map('regex_replace', '^(OS_[^=]+)=(.+)$', '\\1,\\2') | map('split', ',') | map('list')) }}"

- name: Display OpenStack environment
  ansible.builtin.debug:
    var: openstack_env

- name: Verify OpenStack services are operational
  ansible.builtin.command: openstack service list
  environment: "{{ openstack_env }}"
  register: service_list
  changed_when: false

- name: Display OpenStack services
  ansible.builtin.debug:
    var: service_list.stdout_lines
